data:
  class_list_filepath: "./data/libro_animalis/exported/210812_AMMOD_25Classes/ammod-multi-class-list.csv"
  train_list_filepath: "./data/libro_animalis/hakan/ammod-britz-xc-tsa-shorts-with-negs.csv"
  #train_list_filepath: "./data/libro_animalis/hakan/ammod-britz-xc-tsa-shorts-train.csv"
  #train_list_filepath: "./data/libro_animalis/exported/220117_AMMOD_25Classes/ammod-start-end-segment-train.csv"
  val_list_filepath: "./data/libro_animalis/exported/220117_AMMOD_25Classes/ammod-val.csv"
  test_list_filepath: "./data/libro_animalis/exported/220117_AMMOD_25Classes/ammod-val.csv"
  data_root_path: "./data/libro_animalis/"
  #DEVISE
  #class_list_filepath: "./data/libro_animalis/hakan/220326_DEVISE_2Classes/devise-class-list.csv"
  #train_list_filepath: "./data/libro_animalis/hakan/ammod-xc-tsa-shorts-train.csv"
  #val_list_filepath: "./data/libro_animalis/hakan/ammod-xc-tsa-shorts-val.csv"
  #test_list_filepath: "./data/libro_animalis/predictions/xeno-canto-ammod-val/xeno-canto-ammod-val.csv"
  batch_size: 202
  segment_duration: 5.0
  min_event_overlap_time: 0.2
  wrap_around_probability: 0.5

system:
  experiment_name: "220518_AMMOD_25classes_resnet_logging"
  log_dir: "./logs"
  log_every_n_steps: 1
  gpus: [0]
  num_workers: 10
  random_seed: 236742
  deterministic: True
  max_epochs: 380
  fast_dev_run: False
  auto_select_gpus: False #True If you want randomly take free gpu set to true und gpus to an int value > 0

optimizer:
  # optimizers Adam SGD
  optimizer_type: "Adam"
  learning_rate: 0.0004
  sgd_momentum: 0.9
  sgd_weight_decay: 1e-4
  # schedulers None CosineAnnealingLR
  scheduler_type: None #CosineAnnealingLR
  cosine_annealing_lr_t_max: 20

validation:
  complete_segment: True
  segment_step: 1
  batch_size_mulitplier: 3
  check_val_every_n_epoch: 1

audio_loading:
  backend: "soundfile" # 'librosa'
  sample_rate: 32000
  # multi channel handling take_one | take_all | random_mix | to_mono
  channel_mixing_strategy: "to_mono"
  # clyclic | silence
  padding_strategy: "wrap_around"
  fft_size_in_samples: 1536
  fft_hop_size_in_samples: 360
  num_of_mel_bands: 128
  mel_start_freq: 20
  mel_end_freq: 16000
  normalize_mean: 0.456
  normalize_std: 0.224
  use_color_channels: "to_mono"

augmentation:
  # time_mask, frequency_mask, add_background_noise_from_csv, add_gaussian_noise,
  # time_stretch, pitch_shift, shift, add_pink_noise_snr, volume_control, add_same_class_signal
  shuffle_signal_augmentation: False
  signal_pipeline: [
      #"add_same_class_signal",
      #"add_background_noise_from_csv",
      "add_class_signal",
      #"add_pink_noise_snr",
      #"volume_control",
      "frequency_mask",
      "time_mask",
      # "time_stretch",
      #"add_gaussian_noise",
    ]
  # Augmentation Methods Signal

time_mask:
  min_band_part: 0.05
  max_band_part: 0.5
  fade: False
  p: 0.02

frequency_mask:
  min_frequency_band: 0.05
  max_frequency_band: 0.5
  p: 0.02

add_background_noise_from_csv:
  filepath: "./data/libro_animalis/exported/noise_3000.csv"
  data_path: "./data/libro_animalis/"
  index_filepath: 0
  min_snr_in_db: 4
  max_snr_in_db: 10
  delimiter: ";"
  quotechar: "|"
  p: 0.2

add_gaussian_noise:
  min_amplitude: 0.001
  max_amplitude: 0.015
  p: 0.15

time_stretch:
  min_rate: 0.9
  max_rate: 1.10
  leave_length_unchanged: True
  p: 0.20

pitch_shift:
  min_semitones: -2
  max_semitones: 2
  p: 0.20

shift:
  min_fraction: -0.5
  max_fraction: 0.5
  rollover: True
  p: 0.5

add_pink_noise_snr:
  p: 0.2
  min_snr: 3.0
  max_snr: 6.0

volume_control:
  p: 0.2
  db_limit: 6
  # uniform fade cosine sine random
  mode: "cosine"

add_same_class_signal:
  p: 0.2
  min_ssr: -20
  max_ssr: 3
  max_n: 3
  padding_strategy: "wrap_around"
  channel_mixing_strategy: "take_one"
  data_path: "./data/libro_animalis/hakan/"
  data_list_filepath: "./data/libro_animalis/hakan/ammod-xc-tsa-shorts-val.csv"
  # set class_list_filepath if you want to transform into class_index values
  class_list_filepath: "./data/libro_animalis/exported/210812_AMMOD_25Classes/ammod-multi-class-list.csv"
  index_filepath: 1
  index_start_time: 5
  index_end_time: 6
  index_label: 4
  index_channels: 2
  delimiter: ";"
  quotechar: "|"

add_class_signal:
  # Use uniform distribution for probabilities of species during audio mixing 
  #call_probs: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
  # Use weighted distribution. Alphabetic order of species. Based on Olaf Training Annotation
  #call_probs: [0.0022,0.0215,0.058,0.0,0.0836,0.0515,0.0777,0.0058,0.227,0.059,0.0103,0.0506,0.0414,
  #                0.105,0.0033,0.0160,0.0159,0.001,0.0,0.0,0.009,0.0024,0.1248,0.0166,0.018]
  p: 0.3
  restriced_to_same_class: False
  min_ssr: -3
  max_ssr: 3
  max_n: 4
  padding_strategy: "wrap_around"
  channel_mixing_strategy: "take_one"
  data_path: "./data/libro_animalis/hakan/"
  data_list_filepath: "./data/libro_animalis/hakan/ammod-xc-tsa-shorts-val.csv"
  # set class_list_filepath if you want to transform into class_index values
  class_list_filepath: "./data/libro_animalis/exported/210812_AMMOD_25Classes/ammod-multi-class-list.csv"
  index_filepath: 1
  index_start_time: 5
  index_end_time: 6
  index_label: 4
  index_channels: 2
  delimiter: ";"
  quotechar: "|"