version: "2.3"
services:
  torchserve:
    image: bewr42/torchserve:latest-gpu
    #image: pytorch/torchserve:latest-gpu
    restart: unless-stopped
    runtime: nvidia
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 7071:7070
      - 7072:7071
    volumes:
      - ./torchserve/model-store:/home/model-server/model-store
      - ./torchserve/ts_logs:/home/model-server/logs
      - ./torchserve/ts_config:/home/model-server/ts_config
    environment:
      - TS_CONFIG_FILE=/home/model-server/ts_config/config.properties
