version: "2.3"
services:
  torchserve:
    #image: bewr42/torchserve:latest-gpu
    image: bewr42/torchserve:latest-cpu
    restart: unless-stopped
    runtime: nvidia
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 7071:7070
      - 7072:7071
    volumes:
      - ./model-store:/home/model-server/model-store
      - ./ts_logs:/home/model-server/logs
      - ./ts_config:/home/model-server/ts_config
      - ./tmp:/home/model-server/tmp
    environment:
      - TS_CONFIG_FILE=/home/model-server/ts_config/config.properties
      - TEMP_FOLDER=/home/model-server/tmp
